/**
 * ===========================
 * Auto-generated by Sanity CLI
 * ===========================
 * 
 * This file is auto-generated by running:
 * `pnpm sanity:typegen`
 * 
 * Do not edit this file manually.
 * Instead, update your schema in sanity/schemas/
 */

import type {
  SanityReference,
  SanityKeyedReference,
  SanityAsset,
  SanityImage,
  SanityBlock,
  SanityDocument,
  SanityDocumentStub,
} from 'sanity'

export type {
  SanityReference,
  SanityKeyedReference,
  SanityAsset,
  SanityImage,
  SanityBlock,
  SanityDocument,
  SanityDocumentStub,
}

/**
 * Season
 */
export interface Season extends SanityDocument {
  _type: 'season'
  name?: string
  slug?: {
    _type: 'slug'
    current?: string
  }
}

/**
 * Image Reference Object
 */
export interface ImageReference {
  _type: 'imageReference'
  id?: string
  url?: string
}

/**
 * Gallery Image Object
 */
export interface GalleryImage {
  _type: 'object'
  id?: string
  url?: string
}

/**
 * Project
 */
export interface Project extends SanityDocument {
  _type: 'project'
  title?: string
  slug?: {
    _type: 'slug'
    current?: string
  }
  season?: SanityReference<Season>
  category?: 'fastFashion' | 'ready-to-wear' | 'couture'
  description?: string
  image?: ImageReference
  gallery?: Array<GalleryImage>
  publishedAt?: string
}

/**
 * Lookbook
 */
export interface Lookbook extends SanityDocument {
  _type: 'lookbook'
  title?: string
  slug?: {
    _type: 'slug'
    current?: string
  }
  season?: SanityReference<Season>
  category?: 'fastFashion' | 'ready-to-wear' | 'couture'
  description?: string
  image?: ImageReference
  gallery?: Array<GalleryImage>
  publishedAt?: string
}
